export { default as ScientificAbstract } from './ScientificAbstract'
export { default as ProblemStatement } from './ProblemStatement'
export { default as HypothesisCard } from './HypothesisCard'
export { default as VariablesTable } from './VariablesTable'
export { default as MethodologyTimeline } from './MethodologyTimeline'
export { default as ComparisonChart } from './ComparisonChart'
export { default as ExperimentDataTable } from './ExperimentDataTable'
export { default as StatsSummary } from './StatsSummary'
export { default as ConclusionCard } from './ConclusionCard'
export { default as SampleSizeGuidance } from './SampleSizeGuidance'
// Scientific Rigor Components
export { default as BoxPlotChart } from './BoxPlotChart'
export { default as QQPlot } from './QQPlot'
export { default as AssumptionChecksCard } from './AssumptionChecksCard'
export { default as PowerAnalysisCard } from './PowerAnalysisCard'
export { default as EffectSizeCard } from './EffectSizeCard'
