export { default as ScientificAbstract } from './ScientificAbstract'
export { default as ProblemStatement } from './ProblemStatement'
export { default as HypothesisCard } from './HypothesisCard'
export { default as VariablesTable } from './VariablesTable'
export { default as MethodologyTimeline } from './MethodologyTimeline'
export { default as ComparisonChart } from './ComparisonChart'
export { default as ExperimentDataTable } from './ExperimentDataTable'
export { default as ConvergenceDataTable } from './ConvergenceDataTable'
export { default as StatsSummary } from './StatsSummary'
export { default as ConclusionCard } from './ConclusionCard'
// SampleSizeGuidance removed — absorbed into PowerAnalysisCard
// Scientific Rigor Components
export { default as BoxPlotChart } from './BoxPlotChart'
export { default as QQPlot } from './QQPlot'
export { default as AssumptionChecksCard } from './AssumptionChecksCard'
export { default as PowerAnalysisCard } from './PowerAnalysisCard'
export { default as EffectSizeCard } from './EffectSizeCard'
export { default as ConvergenceRangeCard } from './ConvergenceRangeCard'
export { VerificationCard } from './VerificationCard'
export { default as ReferencesSection } from './ReferencesSection'
// Additional Charts for CWSF
export { default as ConvergenceHistogram } from './ConvergenceHistogram'
export { default as ConvergenceMeanBarChart } from './ConvergenceMeanBarChart'
export { default as PairedSeedScatter } from './PairedSeedScatter'

